baseUrl: https://edigo.work/vue
ediGo-AppKey: EdiGoByFounder
accessToken: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjQiLCJ1c2VybmFtZSI6Inlhbnl1ZSIsImlhdCI6MTYzNTIzMjYyMiwiZXhwIjoxNjM1ODM3NDIyfQ.eFo4yG8mNEtDatZDYbJPhoL1FdK1gj6Z13FZzQw05roF31QPvNJT5zfd0uxs2M3E6jSyj-hGybUBWYldDLL4OFe5hLi5oj9nDd0OAcrkHNQ46lWE1DOavvO5Dr7orZrGnTZXC1SxCjTE6Ing5uwz2nMRjQmZ8DyeQcfnExsr6LkNmQFcKpHus1yOXDZKy9m2u1MUaGoQ7smO0FnQuLjlsMq-43VvbY9RzcMSawkXvX4w2QmMspRy20iyDOci8eBQhsdtX5osznDvakY9xdEkPmKc84KVpDvSxdFgNfaeb5VqB8n8YY-GlqnzxpfLbukrMKG_pM0FMl_KTO2nAMPQig
firmId: '1'
publisherId: '1'
refreshToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsImlhdCI6MTYzNTIzMjYyMiwiZXhwIjoxNjM2NDQyMjIyfQ.Pam54OPuYwc6SLWzLpDpXk-C1cNwkauHdzxroWvbbrZ4YTtKPwyX8EahQkRo6miCd1p9XpnCmaC9iTTKKgXJ9_56puA9-6sV_ftf7kPn5A-_a65ARB4NdAq6cfx9S_ymvG2IP2k_ueMsQcGK7VBB8JG54NXak6SJ_VPm6oNUyTacAOVg38Qzf96vcWbNCDgKgavcDSp34HG11kACX6TwXY_Jp2ZFY-5owj0ibHNg7kJgp0W6WtXyNGKL_BgEw7uike1A_wjLu1gyq6Gtp14KLb2D33CRouuPThKVsluS4EL-vP5SEE59RE5-lc3rTcZrapruQU3chBScCsAzAD14nA
roleId: '23'
userId: '24'
userName: yanyue
