baseUrl: http://localhost:8085/vue
ediGo-AppKey: EdiGoByFounder
accessToken: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjQiLCJ1c2VybmFtZSI6Inlhbnl1ZSIsImlhdCI6MTYzNTIyNzY3OSwiZXhwIjoxNjM1ODMyNDc5fQ.ruFRIl1K23aQ337Q0nmjWxvFfycjGhFWmcGzgcpWwnIGusRdDzLHlEGxqF5tlYMSQX25td3AtyDso1UNDMloLKzm-Q1fHqHyNN16VnDUqmIMTYXntdQrdGKvtUcUGczMp3YIpM6SIsYYXNKriQ4HBtmL6zDhn-tHsWLQChkAnU4bHMmxWhRxm2Xc64HslvngQuQA5mtQyFCAme7B01bnhl0xDAWQ0ltooWXFkVJWUrlYaKSGu1ARopZWOKzv-hXddVA46uTNSPBsJyz5oD6Sl95irSE0xrP_XojbqfqTiu5BNymnRJAisqXKtRBXyFDnnwCzTenrcCrzgU5NQwiXYw
firmId: '1'
publisherId: '1'
refreshToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsImlhdCI6MTYzNTIyNzY3OSwiZXhwIjoxNjM2NDM3Mjc5fQ.OvjeJQDXMX2Rx2CElaACYD0xeirxyn1wOPkM8vlA7oEdz7_Cn_zU4LJYZh8b-hjuOOma-8c7KZYWgB9MPCQZYWwCLRZkChtszLzpPb0qIqizxmf3jM0AKk8p-1AHKDWkboRXvAcCUv-POGoSqsHkbjC3mgmxFK83V3_VKH33v8iHYUg4t2YLqhrgBfsrGWozY6ir1AxHcHvLGqdi90DxvtYdOM5TCT1JqKSId5aoPB744P0A7u5z7-xXoyvUJkaadeRJTCZckX_sMSj5vILVcxfZN8FiOGEZUm4FIbKiccW3pafBfSswdtyPChIcxApG2asxr3rDemgjtT347EaMxQ
roleId: '23'
userId: '24'
userName: yanyue
