baseUrl: http://localhost:8085/vue
ediGo-AppKey: EdiGoByFounder
accessToken: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjQiLCJ1c2VybmFtZSI6Inlhbnl1ZSIsImlhdCI6MTYzNTE1NzkzNSwiZXhwIjoxNjM1NzYyNzM1fQ.Bee4BP7hk8E0n9uzouwjtnwpxadaz_sKi_Hf1K9-t0Rjqto2orCcCM-ub7AMn2s5G2xwXn2hNBXGYOlYL-cDednXfxVTjoKYw27NT9HCW-hX-6lCebgFXIP8VFdDFsBEnQ1jHsi7OCq05yHXGgS_M_l4tCFiYAb7__SCCicJkROrqNuOQD9n3Sqvm-Nwbq3wfRn9_5FxTOmrxY0u35Rxcb-5bmy4wPsDfszBofXCs7QeV9JocM_TsGkvebkTQC6iGYubaD-78HZ2Jm0eUkb6iecRLUbw_sc40DojPdG0jOMR7EzYfbDmuMI79CxvkoRSw5XuhxbqwiI_874KyTPD1Q
firmId: '1'
publisherId: '1'
refreshToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsImlhdCI6MTYzNTE1NzkzNSwiZXhwIjoxNjM2MzY3NTM1fQ.HSE_oeErE9yf8GqUaltOx2zlbaY1H3SLFCXTAqdHcfQViL5Qosw7m-gqLLFX5LKiyltjElcrjzK0kE7NjINZqzJybljifpii3Mwtk1e5Zx2hev8kJchVgVpcglgjDZaHgpKBR4Q5bT4WXk9JRaQk9FiS6dWxklv50FICbKS5-jxyaqvcHHmxJgFZ4D6KKSpPFmjrdYfEvzZ-blO0Cr4Q0qb2Ta7FWsjBlaMaZZk9zJRJmw4tt0o-ohRrYnMzv2bohvGMBCO8Wjt35PEUpBvfHz3HRpx0ZxwMz8iuMR4dZw7dIzEsV772diSP4QW2GZ9w1hVsCPF4RwKuuUGVR1-TCQ
roleId: '23'
userId: '24'
userName: yanyue
