baseUrl: http://localhost:8085/vue
ediGo-AppKey: EdiGoByFounder
accessToken: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjQiLCJ1c2VybmFtZSI6Inlhbnl1ZSIsImlhdCI6MTYzNTIxNjMzOSwiZXhwIjoxNjM1ODIxMTM5fQ.pnhOVIjevEaFYvTiGV2OVzAFHJPmeBGYqA48EmyBFX-eHqc3l9UklnKMRmAXg176Zuj6vG9EV_nX0ekGrCxWShE4O6GhxlAcV1Qd_zW3Y7xZ6ta-doKPfJgbm2YpFCGyu_d9cJ84-aJoDt0QKE4VSZ-wuW6h4Esj9IPZGj7geuxL5VlAfohlm3TqFnaTULr5IVzJygDcFgWOLUT1atiHxkMlnXFCY9JNFhjyxNWRIkoCmwAn9O0C8Bui2ajM-GNhA_HiERAJYCHYrgW6pjhVtqCdqKgISp4irNQ9uZ09-qAcotazhRY7acPTvRTOErRA56nGmKECFQ_d9GTvxbVvnQ
firmId: '1'
publisherId: '1'
refreshToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsImlhdCI6MTYzNTIxNjMzOSwiZXhwIjoxNjM2NDI1OTM5fQ.J_A_LWv1spIHfTygWFJYlSoKc976BZ0XjuYPP2bH_Bco7-GsDExffnoow3NRmFMe3IUiRr3XpvDNfP2UsC8dLHLrCDrXRAOF46b-O0XPn8S9wSSDhMmK8nb46SooqY_aN5l07X8fku7ejrU02OcKTC67i3L48sIGnnzjqEFxdQ2YAMj1unW2HJii4eZES5UZguCNXuln9aqUwQ7o_PIE7-2SwUo56M3yPoiEEeKhR6zfV3pLmH9ILwklfQ70V_tal6ibPjK-bt8W_sGH7z-DA9P6EOn1_Q3-E9BFbA4quLm96mHYe4SFNWkKCYlx6m6JiBBNEG5G8N1agQ-dxM6ahw
roleId: '23'
userId: '24'
userName: yanyue
