baseUrl: http://localhost:8085/vue
ediGo-AppKey: EdiGoByFounder
access_token: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjQiLCJ1c2VybmFtZSI6Inlhbnl1ZSIsImlhdCI6MTYzNTE0MDkyNiwiZXhwIjoxNjM1NzQ1NzI2fQ.EgOHV5l4dlIq891kqCvSS09PbJFaJy2yVyh03WkgHWoXaMOkzRnzVGA0o-cNUJ2mgRBfZlCmkUhVZo6EFas2MnpJaIYwl6RKgnWbp97j49rnU8cA8Nv2NgbfrNQwZ_3psQJDy_E5ytnwGj-OcDUiUKWlA_DW0UxvWtXLRdfCtakAoRxB2U89yrn4qXYCPWjNAFVB0BcJGSIREof8urfNMqMvU_kPDY3bqPENb_VO8mI7myL5irarzBDETgJP96EALt4yW-KporzqpRuKJ323_HXbgTuSYdxrE-01_OVfE0_S-VxuTi7PN0dzi1-MrWrQpnK2jk-ypZUP_uTlzZitMw
firmId: 1
publisherId: 1
refresh_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNCIsImlhdCI6MTYzNTE0MDkyNiwiZXhwIjoxNjM2MzUwNTI2fQ.nNwdHKGz6uUdAQMRruOuSf5G6Mzpra2c6BvoxeEoMftC3ehk9lV_D1ySN_xsMb3st-uyrzj6sTHfKgt9a4bdzPSRdorzatp6DIDz9NiEqzz52Xw5XfPLWAehB7mMSMZKDrDZaB-tGTyZrN5h1IYAoXw3MsTVv22LxArEcK8FtJr4g8cEfNUevhSNCFVzWiqsXmVR6fkWGdmqdAIVv_6MXfRCbqK2wC97f6-gF2MShl_1WQV3rILaYQm036DlFPO1nPlRJ6dVH3aZ9ig4JJM1Y382JNhiqd1vtf3aG16CvG_eBk7xWz80RTx_buS8IufuOHork-9LFhD-xG-6hhYmUg
roleId: 23
userId: 24
userName: yanyue
